### PR TITLE
bugfix for bar.setValue and drawRect

### PR DESCRIPTION
**Pull request by fffreedom**
fix bugs: 
1. bar.setValue only accepts int parameter
2. drawRect only accepts 4 int parameters

### CODE REVIEW

**Comment by GreatV** [comment]
Please do not submit PRs to release/2.7. You need to submit them to the main branch.

**Comment by fffreedom** [comment]
> Please do not submit PRs to release/2.7. You need to submit them to the main branch.

The main branch has no PPOCRLabel. I thought the main branch is not newest code.

**Comment by GreatV** [comment]
PPOCRLabel has been moved to https://github.com/PFCCLab/PPOCRLabel

**Comment by GreatV** [comment]
Please submit this PR to https://github.com/PFCCLab/PPOCRLabel if necessary.

**Comment by fffreedom** [comment]
> Please submit this PR to https://github.com/PFCCLab/PPOCRLabel if necessary.

Get. Please update this link also, thanks.

image

**Pull request closed without merging**
