### PR TITLE
fix memory leak

### PR DESCRIPTION
**Pull request by moehuster**

### CODE REVIEW

**Comment by shiyutang** [comment]
Thank you for your contribution, can you provide the procedure to reproduce the memory leak for us to validate the effectiveness of this PR.

**Comment by moehuster** [comment]
Before I provide the procedure to reproduce the memory leak. Let's go to the code itself.
```cpp
  StructureTableRecognizer *table_model_ = nullptr;
  StructureLayoutRecognizer *layout_model_ = nullptr;
```
```cpp
  if (FLAGS_layout) {
    this->layout_model_ = new StructureLayoutRecognizer(
        FLAGS_layout_model_dir, FLAGS_use_gpu, FLAGS_gpu_id, FLAGS_gpu_mem,
        FLAGS_cpu_threads, FLAGS_enable_mkldnn, FLAGS_layout_dict_path,
        FLAGS_use_tensorrt, FLAGS_precision, FLAGS_layout_score_threshold,
        FLAGS_layout_nms_threshold);
  }
  if (FLAGS_table) {
    this->table_model_ = new StructureTableRecognizer(
        FLAGS_table_model_dir, FLAGS_use_gpu, FLAGS_gpu_id, FLAGS_gpu_mem,
        FLAGS_cpu_threads, FLAGS_enable_mkldnn, FLAGS_table_char_dict_path,
        FLAGS_use_tensorrt, FLAGS_precision, FLAGS_table_batch_num,
        FLAGS_table_max_len, FLAGS_merge_no_span_structure);
  }
```
```cpp
PaddleStructure::~PaddleStructure() {
  if (this->table_model_ != nullptr) {
    delete this->table_model_;
  }
}
```
Just like the variable table_model_, layout_model_ is a private member of PaddleStructure. They are all initialized in the constructor. But only table_model_ was deleted in the destructor. There will be a memory leak, If the FLAGS_layout was true. 
IMO, smart pointer `std::unique_ptr` is a better choice.

**Comment by tink2123** [comment]
Thanks for your contribution, can you submit this PR to the dygraph branch？

**Comment by moehuster** [comment]
> Thanks for your contribution, can you submit this PR to the dygraph branch？

A new PR is added #10593, TBR.

**Pull request merged**
