### PR TITLE
Update utils.py

### PR DESCRIPTION
**Pull request by Azzer8**
For seveRecRes, so that the cropped images are smooth, not inverted. If an area was incorrectly marked up, for example, the areas were highlighted not from the top left, but from the bottom left or otherwise

### CODE REVIEW

**Review by GreatV — COMMENTED** [review]
Please commit to the `main` branch and remove the comments.

**Comment by GreatV** [comment]
hi @Azzer8 You may need to resubmit a PR, checkout from the main branch.

**Comment by GreatV** [comment]
PPOCRLabel has been moved to https://github.com/PFCCLab/PPOCRLabel

**Comment by Azzer8** [comment]
should I create a PR in this repository?

**Comment by GreatV** [comment]
@Azzer8  That would be best.

**Comment by Azzer8** [comment]
Ok, thanks

**Comment by GreatV** [comment]
PPOCRLabel has been moved to https://github.com/PFCCLab/PPOCRLabel

**Pull request closed without merging**
