### PR TITLE
fix "No module named xxx" error after built target executable file by Pyinstaller and run.

### PR DESCRIPTION
**Pull request by kerneltravel**
fix "No module named xxx" error after built target executable file by Pyinstaller and run. the related issue ID is #10398, #10340, #9951, #9723 #9694. according to the suggestion from issue #9408.

### CODE REVIEW

**Review by onecatcn — APPROVED** [review]
LGTM

**Comment by shiyutang** [comment]
@kerneltravel 
I cannot reproduce the error as shown in those issues, can you point out a way to reproduce the issues such that I can examine this PR is correct?

**Review by shiyutang — COMMENTED** [review]
@kerneltravel
I cannot reproduce the error as shown in those issues, can you point out a way to reproduce the issues such that I can examine this PR is correct?

**Comment by shiyutang** [comment]
I have executed the following command, which didn't report an error as shown in the image.
```python
pyinstaller -F main.py 
# Add the following script in the main.spec as it cued in the above scripts' output
# import sys; sys.setrecursionlimit(sys.getrecursionlimit() * 5) 

pyinstaller main.spec
```

image

**Comment by kerneltravel** [comment]
the error happend when dist/project_name/project_name.exe file execute. I'll paste a issue-demo project in github.com as soon as possible. please wait for a moment

**Comment by kerneltravel** [comment]
can not re-produce . will close this PR

**Comment by xuri422** [comment]
I can re-produce this bug.

**Comment by onecatcn** [comment]
I am reopenning the PR. Though the PR contributor and the review cannot reproduce the bug, but the bug was discussed in several previous issues, and other user are saying they are having the bug. 
It can be closed after the discussion reach a conclusion. We encourage more users share their views on this topic.

**Comment by xuri422** [comment]
**1、 my source code in: test.py**
import os
import sys
from paddleocr import PaddleOCR, draw_ocr

# Paddleocr目前支持的多语言语种可以通过修改lang参数进行切换
# 例如`ch`, `en`, `fr`, `german`, `korean`, `japan`
ocr = PaddleOCR(use_angle_cls=True, lang="ch")  # need to run only once to download and load model into memory
img_path = 'C:/Code/ppocr_img/imgs/11.jpg'
result = ocr.ocr(img_path, cls=True)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)

# 显示结果
# 如果本地没有simfang.ttf，可以在doc/fonts目录下下载
from PIL import Image
result = result[0]
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores, font_path='doc/fonts/simfang.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')

**2、Enviroment:**
python:  Python 3.8.9  or Python 3.10.4
pip list:
.......
numpy                     1.24.4
opencv-contrib-python     4.6.0.66
opencv-python             4.6.0.66
openpyxl                  3.1.2
opt-einsum                3.3.0
packaging                 23.1
paddle-bfloat             0.1.7
paddleocr                 2.6.1.3
paddlepaddle              2.5.0
pandas                    2.0.3
pdf2docx                  0.5.6
pefile                    2023.2.7
Pillow                    10.0.0
pip                       23.2
premailer                 3.10.0
protobuf                  3.20.2
psutil                    5.9.5
pyclipper                 1.3.0.post4
pycryptodome              3.18.0
pyinstaller               5.13.0
pyinstaller-hooks-contrib 2023.5
...........


**3、pyinstaller -F .\test.py**
then generate test.exe in dist directory.


**4、running in command line:**
C:\Code\Test\dist>test.exe
Traceback (most recent call last):
  File "test.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "paddleocr\__init__.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "paddleocr\paddleocr.py", line 35, in <module>
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'paddleocr.ppstructure'
[5428] Failed to execute script 'test' due to unhandled exception!

**Comment by xuri422** [comment]
> > 
> 
> @xuri422 what are the OS you've tested ?

Win10 Professional x64 (22H2) 19045.3086

**Comment by kerneltravel** [comment]
as @xuri422 code (updated :)
```
# file name : main.py
import os
import sys
from pathlib import Path
from paddleocr import PaddleOCR, draw_ocr

ocr = PaddleOCR(use_angle_cls=True, lang="ch") # need to run only once to download and load model into memory
img_path = str(Path(os.getcwd()) / '11.jpg')
result = ocr.ocr(img_path, cls=True)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)

from PIL import Image
result = result[0]
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores, font_path='doc/fonts/simfang.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')

```
build by ` pyinstaller  -F main.py`  ,and got dist/main.exe

the output reproduce the issue:
```
(python38_64bit_venv) 
$ pwd
/windows/d/data/path/main/dist

$ ./main.exe
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "paddleocr\__init__.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "paddleocr\paddleocr.py", line 33, in <module>
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'tools'
[36268] Failed to execute script 'main' due to unhandled exception!

(python38_64bit_venv) 
$ ls
11.jpg  main.exe*

```

**Comment by kerneltravel** [comment]
> as @xuri422 code (updated :)
> 
> ```
> # file name : main.py
> import os
> import sys
> from pathlib import Path
> from paddleocr import PaddleOCR, draw_ocr
> 
> ocr = PaddleOCR(use_angle_cls=True, lang="ch") # need to run only once to download and load model into memory
> img_path = str(Path(os.getcwd()) / '11.jpg')
> result = ocr.ocr(img_path, cls=True)
> for idx in range(len(result)):
>     res = result[idx]
>     for line in res:
>         print(line)
> 
> from PIL import Image
> result = result[0]
> image = Image.open(img_path).convert('RGB')
> boxes = [line[0] for line in result]
> txts = [line[1][0] for line in result]
> scores = [line[1][1] for line in result]
> im_show = draw_ocr(image, boxes, txts, scores, font_path='doc/fonts/simfang.ttf')
> im_show = Image.fromarray(im_show)
> im_show.save('result.jpg')
> ```
> 
> build by ` pyinstaller -F main.py` ,and got dist/main.exe
> 
> the main.exe runtime output reproduce the issue:
> 
> ```
> (python38_64bit_venv) 
> $ pwd
> /windows/d/data/path/main/dist
> 
> $ ./main.exe
> Traceback (most recent call last):
>   File "main.py", line 4, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
>   File "paddleocr\__init__.py", line 14, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
>   File "paddleocr\paddleocr.py", line 33, in <module>
>   File "importlib\__init__.py", line 127, in import_module
> ModuleNotFoundError: No module named 'tools'
> [36268] Failed to execute script 'main' due to unhandled exception!
> 
> (python38_64bit_venv) 
> $ ls
> 11.jpg  main.exe*
> ```
> 
> for detailed steps , I'd create a [repository](https://github.com/kerneltravel/PaddleOCR_PR10421_reproduce) which shows that ,after adopt PR10421 's fixed-code, and rebuild ( python to_exe.py ) ,the final exe runs successfully.
> 
> may you try this repo's method, and hope to find the real bug. https://github.com/kerneltravel/PaddleOCR_PR10421_reproduce
> 
> some more test is required.
> 
> @onecatcn @shiyutang

When using the `import` or `from ... import ...` statement to import a module file within a package, Python searches for the corresponding module file in the package search path. Typically, the package search path includes the **current directory, directories specified in the `PYTHONPATH` environment variable, and the `site-packages` directory in the Python installation directory**. If the module file does not exist in any of these paths, an import error will occur.

for Pyinstaller packaged executed file, the package 
-----
case 1. ```
from tools.infer.utility import draw_ocr_box_txt, str2bool, init_args as infer_args
```
VS

case 2. ```
from paddleocr.tools.infer.utility import draw_ocr_box_txt, str2bool, init_args as infer_args
```
---------
in case 1, the tools package is not in the search path, so will got error "no modules found: tools".
this will not happen when the source code file interpreted run by command line python, 


in case 2, the tools package can be found under package paddleocr, so will not got "no modules found: tools".


Why does it seem like the rules of the "three search paths"  are not followed when loading packages and modules in code run directly with `python.exe`? When running Python code with `python.exe`, it needs to load third-party packages, but the packages imported by the third-party package are other packages within that third-party package, and the import paths do not start with the name of that third-party package. However, everything works fine in this case. How can this be explained?

This situation  may be due to the fact that in Python, the search path of packages can be modified through the `sys.path` variable. `sys.path` is a list of strings that specifies which directories the Python interpreter should look for when searching for modules. When the Python interpreter starts, it automatically adds the current directory to `sys.path`, so when running some scripts, you may find that they can import some third-party packages that are not in the standard search path.

For third-party packages, they are usually installed in the `site-packages` directory of Python, which is ordered in `sys.path`. This means that if you want to specify a custom search path when importing a third-party package, you can add a new directory to `sys.path` and place it before the `site-packages` directory. In this way, when you try to import a third-party package, the Python interpreter will first search the directory you specified. If it finds the corresponding package, it will import it; otherwise, it will search the `site-packages` directory.

It should be noted that although the `sys.path` variable can be modified to specify the search path of the Python interpreter, this is not a recommended practice. In general, the standard search path should be used as much as possible, otherwise, you may encounter some unexpected problems. If you need to use a custom search path, it is best to limit it to specific scripts or projects, rather than modifying `sys.path` system-wide.

in paddleOCR package, the `https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/paddleocr.py`  currently use the sys.path way:

```
import os
import sys
import importlib

__dir__ = os.path.dirname(__file__)

import paddle

sys.path.append(os.path.join(__dir__, ''))

import cv2
import logging
import numpy as np
from pathlib import Path

def _import_file(module_name, file_path, make_importable=False):
    spec = importlib.util.spec_from_file_location(module_name, file_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    if make_importable:
        sys.modules[module_name] = module
    return module

tools = _import_file('tools', os.path.join(__dir__, 'tools/__init__.py'), make_importable=True)
ppocr = importlib.import_module('ppocr', 'paddleocr')
ppstructure = importlib.import_module('ppstructure', 'paddleocr')

from tools.infer import predict_system
from ppocr.utils.logging import get_logger

logger = get_logger()
from ppocr.utils.utility import check_and_read, get_image_file_list, alpha_to_color, binarize_img
from ppocr.utils.network import maybe_download, download_with_progressbar, is_link, confirm_model_dir_url
from tools.infer.utility import draw_ocr, str2bool, check_gpu
from ppstructure.utility import init_args, draw_structure_result
from ppstructure.predict_system import StructureSystem, save_structure_res, to_excel
……
```

**Comment by kerneltravel** [comment]
what need to be done? any suggestion is appreciated .

**Comment by kerneltravel** [comment]
@LDOUBLEV when are you online and convinent to review this PR? 
@onecatcn @shiyutang is there any latest suggestions for this PR?

**Comment by onecatcn** [comment]
> @LDOUBLEV when are you online and convinent to review this PR? @onecatcn @shiyutang is there any latest suggestions for this PR?

I talked to the RD from PaddleOCR, and she does not feel it is the right way to resolve the issue. And thus, I was not able to merge the PR.

We will have a online meetup today (and the meetup is for people interested in PaddleCV and is held weekly). I think you can put this PR in the open discussion session. And of course, I sincerely welcome you to join our group.

You can get more information via this wechat group
image

**Comment by kerneltravel** [comment]
the root cause is clear now.  it has been noted at this repository: https://github.com/kerneltravel/PaddleOCR_PR10421_reproduce .

no need to append module path prefix to existing submodules of paddleOCR, I will close PR 10421.
but two lines of code files ( including paddleocr\ppocr\utils\utility.py 、paddleocr\ppocr\data\imaug\ct_process.py ) has import unused module which that line need be clean, to avoid pyinstaller package binray throw module ( the third-party module including `import imghdr` and `import scipy.io as scio`) not found error, I'll open new PR for it.

**Comment by kerneltravel** [comment]
those who want to package python application include paddleocr by pyinstall may referer to [this](https://github.com/kerneltravel/PaddleOCR_PR10421_reproduce/commit/7ccfed344e88e371ee744a335e7dd4b3fff0ffca) to  append parameter `--collect-all paddleocr `  to pyinstaller . 

`--collect-all MODULE_NAMES` means `Collect all submodules, data files, and binaries from the specified package or module. This option can be used multiple times`.

**Comment by Suvoo** [comment]
This is a great solution, might miss some corner cases with dll files,
perfectly working solution (August 2024) : https://github.com/PaddlePaddle/PaddleOCR/discussions/11342

Tl,DR :
`pyinstaller main.py --collect-all paddleocr --collect-all pyclipper --collect-all imghdr --collect-all skimage --collect-all imgaug --collect-all scipy.io --collect-all lmdb`

**Pull request closed without merging**
