### PR TITLE
fix: 'numpy' has no attribute 'astype'

### PR DESCRIPTION
**Pull request by laolitou**
修复fastdeploy中的异常

### CODE REVIEW

**Review by GreatV — APPROVED** [review]
LGTM

**Comment by GreatV** [comment]
hi @laolitou, CLA is not signed yet.

**Comment by laolitou** [comment]
> hi @laolitou, CLA is not signed yet.

All right

**Comment by laolitou** [comment]
> hi @laolitou, CLA is not signed yet.

image
image
我已经同意了  但还是显示没同意

**Comment by GreatV** [comment]
@laolitou 你本地的用户名和github的用户名不一致

**Pull request closed without merging**
