### PR TITLE
bugfixed: deploy/slim/quantization/export_model.py import error

### PR DESCRIPTION
**Pull request by yes-github**

### CODE REVIEW

**Comment by GreatV** [comment]
为啥要改这里呀

**Comment by yes-github** [comment]
> 为啥要改这里呀

引用地址错误了，运行报错

**Review by GreatV — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
@yes-github  Thanks for your contribution! You will receive a beautiful PaddlePaddle gift. Please fill out the following questionnaire before Jan 24th to provide your mailing address.

Looking forward to the future, we will walk further together in the open source world!
Click Here：https://paddle.wjx.cn/vm/e5X5nYI.aspx#

**Pull request merged**
