### PR TITLE
Burmese Language dict and corpus

### PR DESCRIPTION
**Pull request by 1chimaruGin**
Added 

- `ppocr/utils/dict/bm_dict.txt`: 160 characters 
      - `Ln65-74` - number 0 to 9
      - `Ln75-76` - `၊` and  `။` which are punctuation mark similar to `,` and `.`.
      - For more information, please refer to https://en.wikipedia.org/wiki/Burmese_alphabet.

- Created a repository for Burmese corpus. Please see [https://github.com/1chimaruGin/BurmeseCorpus](https://github.com/1chimaruGin/BurmeseCorpus).

### CODE REVIEW

**Review by jzhang533 — APPROVED** [review]
LGTM after adding a statement in ppocr/utils/dict/README.md

**Comment by luotao1** [comment]
@1chimaruGin Thanks for your contribution! You will receive a beautiful PaddlePaddle gift. Please provide your mailing address by filling out the following questionnaire before October 18th.

Looking forward to the future, we will walk further together in the world of open source!
Click Here ：https://paddle.wjx.cn/vm/h4On9gJ.aspx#

**Comment by luotao1** [comment]
@1chimaruGin, Could you provide your phone number? We need this information when mailing gifts. Please send your phone number to ext_paddle_oss@baidu.com. Thanks very much!

**Comment by luotao1** [comment]
@1chimaruGin Could you provide your email? We need this information when mailing gifts. Please send your email to [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com) or here. Thanks very much!

**Pull request merged**
