### PR TITLE
Fixed bug with "max_text_length" for VisionLAN

### PR DESCRIPTION
**Pull request by victor30608**
cherry-pick of https://github.com/PaddlePaddle/PaddleOCR/pull/10962

### CODE REVIEW

**Comment by victor30608** [comment]
@shiyutang

**Comment by shiyutang** [comment]
no, the CI has its own problem, we will fix it soon ~

**Comment by victor30608** [comment]
> no, the CI has its own problem, we will fix it soon ~

Can u approve my PR ?

**Review by shiyutang — APPROVED** [review]
LGTM

**Pull request merged**
