### PR TITLE
refactored splitTrainVal and added multiOS path support

### PR DESCRIPTION
**Pull request by itasli**

### CODE REVIEW

**Comment by andyjpaddle** [comment]
@itasli could you explain your PR ? I'm confused about what you have changed?

**Comment by itasli** [comment]
Hey @andyjpaddle , basically I changed this :

```
imagePath = os.path.join(dataAbsPath, "{}\\{}".format(args.recImageDirName, imageName))
```

to this :

```
image_path = os.path.join(data_abs_path, args.recImageDirName, image_name)
```

I don't really remember well but i had some issue using the split function on either windows or ubuntu and had to modifiy the code to make it word, other changes are just refactoring

**Comment by shiyutang** [comment]
Hi, Could you please push your changes to the dygraph branch.

**Comment by itasli** [comment]
> Hi, Could you please push your changes to the dygraph branch.

here it is GH-11069

**Comment by shiyutang** [comment]
This PR have been merged into develop. Therefore close it.

**Pull request closed without merging**
