### PR TITLE
Cherrypicking GH-10217 and GH-10216 to PaddlePaddle:dygraph

### PR DESCRIPTION
**Pull request by UserUnknownFactor**

### CODE REVIEW

**Review by shiyutang — APPROVED** [review]
LGTM

**Comment by UserUnknownFactor** [comment]
@shiyutang What's happening with this PR?

**Comment by shiyutang** [comment]
Don't worry, we just need to wait for the CI

**Review by shiyutang — APPROVED** [review]
LGTM

**Pull request merged**
