### PR TITLE
Slovak language request

### PR DESCRIPTION
**Pull request by MatKollar**
### Slovak language request

Added dict and corpus file to request Slovak language for text recognition.

### CODE REVIEW

**Comment by onecatcn** [comment]
@MatKollar could you please resubmit a PR to the dygraph branch?

**Comment by MatKollar** [comment]
@onecatcn Yes of course

**Comment by onecatcn** [comment]
@MatKollar I am sorry for the inappropriate reply I put earlier today. You don't need to submit any more PR regarding this topic. The filles are well received and I have included this request in the [Multilingual OCR Development Plan ](https://github.com/PaddlePaddle/PaddleOCR/issues/1048).

**Comment by MatKollar** [comment]
@onecatcn OK, thank you.

**Pull request closed without merging**
