### PR TITLE
Add support for Hebrew Language and Alphabet

### PR DESCRIPTION
**Pull request by johnlockejrr**
https://en.wikipedia.org/wiki/Unicode_and_HTML_for_the_Hebrew_alphabet

Hebrew is like Arabic a RTL Language.

### CODE REVIEW

**Review by johnlockejrr — COMMENTED** [review]
Seems like the script failed beeing killed

**Review by GreatV — COMMENTED** [review]
please fix codestyle

**Comment by johnlockejrr** [comment]
Fixed

**Review by GreatV — APPROVED** [review]
LGTM

**Comment by ephraimm** [comment]
Hi @johnlockejrr

I'd like to test the hebrew support, but having trouble getting a compiled version working to test. could you point me in the right direction.

many thanks

**Comment by johnlockejrr** [comment]
I didn't train yet a model for Hebrew on PaddleOCR, got stuck on work with YOLOv8 and PyLaia and kraken for Hebrew

**Comment by luotao1** [comment]
@johnlockejrr Thanks for your contribution! You will receive a beautiful PaddlePaddle gift. Please provide your mailing address by filling out the following questionnaire before October 18th.

Looking forward to the future, we will walk further together in the world of open source!
Click Here ：https://paddle.wjx.cn/vm/h4On9gJ.aspx#

**Comment by ephraimm** [comment]
Is there anyway I can help. What are the next steps?

**Comment by johnlockejrr** [comment]
@ephraimm, sure, I'm right now collecting as much ground-truth/datasets of very good quality for Hebrew. In my case, I mostly work with ancient/medieval Hebrew (bIblical, rabbinical, responsa etc. stuff) but Ivrit also. We can collaborate if you want.

**Comment by johnlockejrr** [comment]
> @johnlockejrr Thanks for your contribution! You will receive a beautiful PaddlePaddle gift. Please provide your mailing address by filling out the following questionnaire before October 18th.
> 
> Looking forward to the future, we will walk further together in the world of open source! Click Here ：https://paddle.wjx.cn/vm/h4On9gJ.aspx#

I'm not born today

**Comment by ephraimm** [comment]
@johnlockejrr  we're after the same thing.
My end game is to digitise printed (chassidic) texts that usually have complex section breaks and columns. I have had some success combining tesseract with google vision, but this is not ideal and would like to find an open source solution.

tesseract is good at recognising blocks, but not good at distinguishing between actual text and subscript references to footnotes and punctuation. google on the other hand is great at accurately recognising the characters but doesn't recognise column breaks etc.

My current hypothesis is if I give tesseract a good quality sample of text from google and fine tune the existing Hebrew model we'll get the results.

What makes you think paddle will work? Have you tried fine tuning tesseract?

**Comment by johnlockejrr** [comment]
Drop me an email [at] gmail.com

**Comment by ephraimm** [comment]
@johnlockejrr 
sent to gee male. you can do likewise

**Comment by luotao1** [comment]
@johnlockejrr Could you provide your email? We need this information when mailing gifts. Please send your email to [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com) or here. Thanks very much!

**Comment by johnlockejrr** [comment]
@luotao1 is: johnlockejrr [at] gmail.com

**Pull request merged**
