### PR TITLE
修改错别字

### PR DESCRIPTION
**Pull request by MonkeyBrothers**
修改README中的错别字

### CODE REVIEW

**Comment by GreatV** [comment]
hi @MonkeyBrothers, CLA is not signed yet.

**Review by SWHL — COMMENTED** [review]
LGTM

**Review by GreatV — APPROVED** [review]
LGTM

**Comment by luotao1** [comment]
@MonkeyBrothers Thanks for your contribution! You will receive a beautiful PaddlePaddle gift. Please provide your mailing address by filling out the following questionnaire before October 18th.

Looking forward to the future, we will walk further together in the world of open source!
Click Here ：https://paddle.wjx.cn/vm/h4On9gJ.aspx#

**Pull request merged**
