### PR TITLE
Bug with "max_text_length" for VisionLAN 

### PR DESCRIPTION
**Pull request by victor30608**
Fixed a bug where changing max_text_length for VisionLAN did not change the length of the output text

### CODE REVIEW

**Comment by andyjpaddle** [comment]
@victor30608 thanks for your PR, would you mind push your change to branch `dygraph` and then cherry-pick to `release 2.7`?

**Comment by victor30608** [comment]
@andyjpaddle

**Comment by andyjpaddle** [comment]
> @andyjpaddle Please explain in more detail what I need to do

@victor30608 you need push your code into branch [dygraph](https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph)

**Comment by shiyutang** [comment]
close this PR due to merged the identical PR to the dygraph branch.

**Pull request closed without merging**
