### PR TITLE
Dictionary and Corpus are added for Bangla

### PR DESCRIPTION
**Pull request by taeefnajib**
Bangla dictionary `bn_dict.txt` has been added to `ppocr/utils/dict` and corpus `bn_corpus.txt` has been added to `ppocr/utils/corpus`
Details about Bangla language can be found [here](https://en.wikipedia.org/wiki/Bengali_language) and [here](https://en.wikipedia.org/wiki/Bengali_alphabet). `bn_corpus.txt` file contains 454788 words and `bn_dict.txt` file contains all the numbers, vowels, consonants, punctuation, special characters and joint letters.
I would love to get your feedback on this PR. Adding Bangla to PaddleOCR is very important for me to work on Bangla text detection related projects. Thanks.

### CODE REVIEW

**Comment by taeefnajib** [comment]
Any feedback from you guys?

**Comment by taeefnajib** [comment]
I thought it'd be nice to have multi-language support in PaddleOCR

**Comment by taeefnajib** [comment]
@shiyutang any feedback from you?

**Comment by alimify** [comment]
Hi there, any update on it ?

**Comment by taeefnajib** [comment]
No! They didn't merge the branch

**Comment by GreatV** [comment]
hi @taeefnajib, Would it be possible to recommit this pr to the `main` branch and we will merge into that branch.

**Comment by taeefnajib** [comment]
Hi @GreatV I will recommit this pr to the `main` branch. I think the language code for Bangladesh should be `bn` instead of `bg` (which is the code for Bulgarian) in [this post](https://github.com/PaddlePaddle/PaddleOCR/issues/1048). I don't see a `corpus` folder inside `ppocr/utils`. However I'll add `bn_dict.txt`

**Comment by taeefnajib** [comment]
@alimify I created a new PR #13373

**Pull request closed without merging**
