### PR TITLE
[third-party] Fix the issue of inference errors with KE models in ONNX format

### PR DESCRIPTION
**Pull request by Alex37882388**
@ZeyuChen 这个模型的inputs有4个，但原代码中使用onnx推理时仅使用了1个，在推理时会报错。
本次PR修改input为4个，并兼容了paddleInfer和onnx输出的output获取方式。
issue请参阅:
- #14107

### CODE REVIEW

**Comment by GreatV** [comment]
please fix codestyle and sign CLA

**Comment by GreatV** [comment]
It's recommended to write a unit test to verify that this modification does not introduce new issues when invoking the PPOCRv4 and PP-Structure models with ONNX.

**Comment by GreatV** [comment]
please sign the CLA.

**Comment by Alex37882388** [comment]
I have agreed to the CLA for PaddlePaddle/PaddleOCR.

**Comment by GreatV** [comment]
> You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.

**Review by GreatV — COMMENTED** [review]
work well for me

```bash
mkdir inference && cd inference
# download model
wget https://paddleocr.bj.bcebos.com/ppstructure/models/vi_layoutxlm/ser_vi_layoutxlm_xfund_infer.tar && tar -xf ser_vi_layoutxlm_xfund_infer.tar

cd ../ppstructure

python3 predict_system.py \
  --kie_algorithm=LayoutXLM \
  --ser_model_dir=../inference/ser_vi_layoutxlm_xfund_infer \
  --image_dir=./docs/kie/input/zh_val_42.jpg \
  --ser_dict_path=../ppocr/utils/dict/kie_dict/xfund_class_list.txt \
  --vis_font_path=../doc/fonts/simfang.ttf \
  --ocr_order_method="tb-yx" \
  --mode=kie

paddle2onnx --model_dir ./inference/ser_vi_layoutxlm_xfund_infer \
--model_filename inference.pdmodel \
--params_filename inference.pdiparams \
--save_file ./inference/ser_vi_layoutxlm_xfund_infer/model.onnx \
--opset_version 11 \
--enable_onnx_checker True

python3 kie/predict_kie_token_ser.py \
    --kie_algorithm=LayoutXLM \
    --use_onnx=True \
    --mode=kie \
    --ser_model_dir=../inference/ser_vi_layoutxlm_xfund_infer/model.onnx \
    --image_dir=./docs/kie/input/zh_val_42.jpg \
    --ser_dict_path=../ppocr/utils/dict/kie_dict/xfund_class_list.txt \
    --ocr_order_method="tb-yx" \
    --det_model_dir=../inference/ch_PP-OCRv4_det_infer/ \
    --rec_model_dir=../inference/ch_PP-OCRv4_rec_infer/  \
    --cls_model_dir=../inference/ch_ppocr_mobile_v2.0_cls_infer/ \
    --vis_font_path=../doc/fonts/simfang.ttf

python3 kie/predict_kie_token_ser.py \
    --kie_algorithm=LayoutXLM \
    --use_onnx=False \
    --mode=kie \
    --ser_model_dir=../inference/ser_vi_layoutxlm_xfund_infer/ \
    --image_dir=./docs/kie/input/zh_val_42.jpg \
    --ser_dict_path=../ppocr/utils/dict/kie_dict/xfund_class_list.txt \
    --ocr_order_method="tb-yx" \
    --det_model_dir=../inference/ch_PP-OCRv4_det_infer/ \
    --rec_model_dir=../inference/ch_PP-OCRv4_rec_infer/  \
    --cls_model_dir=../inference/ch_ppocr_mobile_v2.0_cls_infer/ \
    --vis_font_path=../doc/fonts/simfang.ttf

```

```text
[2024/11/01 16:08:04] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[2024/11/01 16:08:04] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[2024-11-01 16:08:05,992] [    INFO] - tokenizer config file saved in /home/greatx/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2024-11-01 16:08:05,993] [    INFO] - Special tokens file saved in /home/greatx/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
Corrupt JPEG data: premature end of data segment
[2024/11/01 16:08:09] ppocr INFO: save vis result to ./output/zh_val_42.jpg
[2024/11/01 16:08:09] ppocr INFO: Predict time of ./docs/kie/input/zh_val_42.jpg: 0.23263001441955566
[2024/11/01 16:08:11] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[2024/11/01 16:08:11] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
[2024-11-01 16:08:13,096] [    INFO] - tokenizer config file saved in /home/greatx/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2024-11-01 16:08:13,096] [    INFO] - Special tokens file saved in /home/greatx/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2024/11/01 16:08:13] ppocr WARNING: The first GPU is used for inference by default, GPU ID: 0
Corrupt JPEG data: premature end of data segment
[2024/11/01 16:08:15] ppocr INFO: save vis result to ./output/zh_val_42.jpg
[2024/11/01 16:08:15] ppocr INFO: Predict time of ./docs/kie/input/zh_val_42.jpg: 0.06023693084716797
```

**Comment by GreatV** [comment]
for ppocr

```bash
paddle2onnx --model_dir ./inference/ch_PP-OCRv3_det_infer \
--model_filename inference.pdmodel \
--params_filename inference.pdiparams \
--save_file ./inference/ch_PP-OCRv3_det_infer/model.onnx \
--opset_version 11 \
--enable_onnx_checker True

paddle2onnx --model_dir ./inference/ch_PP-OCRv3_rec_infer \
--model_filename inference.pdmodel \
--params_filename inference.pdiparams \
--save_file ./inference/ch_PP-OCRv3_rec_infer/model.onnx \
--opset_version 11 \
--enable_onnx_checker True

paddle2onnx --model_dir ./inference/ch_ppocr_mobile_v2.0_cls_infer \
--model_filename inference.pdmodel \
--params_filename inference.pdiparams \
--save_file ./inference/ch_ppocr_mobile_v2.0_cls_infer/model.onnx \
--opset_version 11 \
--enable_onnx_checker True

python3 tools/infer/predict_system.py --use_gpu=False --use_onnx=True \
--det_model_dir=./inference/ch_PP-OCRv3_det_infer/model.onnx \
--rec_model_dir=./inference/ch_PP-OCRv3_rec_infer/model.onnx  \
--cls_model_dir=./inference/ch_ppocr_mobile_v2.0_cls_infer/model.onnx  \
--image_dir=./deploy/lite/imgs/lite_demo.png


paddle2onnx --model_dir ./inference/ch_PP-OCRv4_det_infer \
--model_filename inference.pdmodel \
--params_filename inference.pdiparams \
--save_file ./inference/ch_PP-OCRv4_det_infer/model.onnx \
--opset_version 11 \
--enable_onnx_checker True

paddle2onnx --model_dir ./inference/ch_PP-OCRv4_rec_infer \
--model_filename inference.pdmodel \
--params_filename inference.pdiparams \
--save_file ./inference/ch_PP-OCRv4_rec_infer/model.onnx \
--opset_version 11 \
--enable_onnx_checker True

paddle2onnx --model_dir ./inference/ch_ppocr_mobile_v2.0_cls_infer \
--model_filename inference.pdmodel \
--params_filename inference.pdiparams \
--save_file ./inference/ch_ppocr_mobile_v2.0_cls_infer/model.onnx \
--opset_version 11 \
--enable_onnx_checker True

python3 tools/infer/predict_system.py --use_gpu=False --use_onnx=True \
--det_model_dir=./inference/ch_PP-OCRv4_det_infer/model.onnx \
--rec_model_dir=./inference/ch_PP-OCRv4_rec_infer/model.onnx  \
--cls_model_dir=./inference/ch_ppocr_mobile_v2.0_cls_infer/model.onnx  \
--image_dir=./deploy/lite/imgs/lite_demo.png
```

**Comment by luotao1** [comment]
@Alex37882388  Thanks for your contribution! You will receive a beautiful PaddlePaddle gift. Please fill out the following questionnaire before Jan 24th to provide your mailing address.

Looking forward to the future, we will walk further together in the open source world!
Click Here：https://paddle.wjx.cn/vm/e5X5nYI.aspx#

**Pull request merged**
