### PR TITLE
add faq toc

### PR DESCRIPTION
**Pull request by mattheliu**
add faq toc

### CODE REVIEW

**Comment by GreatV** [comment]
Do you mean removing the FAQ table of contents?

**Comment by SWHL** [comment]
That means show the toc contents in the right side of the [FAQ page](https://paddlepaddle.github.io/PaddleOCR/latest/FAQ.html#qshape).

**Comment by GreatV** [comment]
This will cause a lot of visual confusion.

**Comment by SWHL** [comment]
A little bit indeed.

**Comment by mattheliu** [comment]
yes,i think so

**Pull request closed without merging**
