### PR TITLE
[WIP]merge uapi paddleocr

### PR DESCRIPTION
**Pull request by zhangyubo0722**

### CODE REVIEW

**Comment by jzhang533** [comment]
please submit your work to main branch.
and, what is uapi ?

I will convert it to draft, since it's wip.

**Comment by zhangyubo0722** [comment]
> please submit your work to main branch. and, what is uapi ?
> 
> I will convert it to draft, since it's wip.

This PR needs to synchronize the internal changes of pdx to the open source repo. After communicating with PaddleOCR developers, we plan to merge it into the 2.6.1 branch. We hope that this PR will be merged as soon as possible. Thank you.

**Comment by jzhang533** [comment]
Merging this patch to release/2.6.1 is an urgent request by @cuicheng01 from Baidu. Sure, we can merge it.

It would be helpful if PR author and stakeholders can explain the following:

- what's the future plan for release/2.6.1 branch? if it will be used for internal fixes, probably we should rename it to a meaningful branch name.
- is this change related to [paddlex](https://github.com/PaddlePaddle/PaddleX) ?
- what is uapi ?

**Comment by GreatV** [comment]
Does this change require a cherry pick to the main branch?

**Comment by cuicheng01** [comment]
"release/2.6.1" is the stable branch of PaddleOCR for [PaddleX](https://github.com/PaddlePaddle/PaddleX) dependencies. The new version of PaddleX will be open sourced at the end of May. This change is just a minor modification to the 2.6.1 branch that PaddleX previously relied on."uapi" is the core code of PaddleX. 
We don't think it's necessary to update the main branch. Of course, we can listen to @jzhang533 's advice.

**Comment by jzhang533** [comment]
> "release/2.6.1" is the stable branch of PaddleOCR for [PaddleX](https://github.com/PaddlePaddle/PaddleX) dependencies. The new version of PaddleX will be open sourced at the end of May. This change is just a minor modification to the 2.6.1 branch that PaddleX previously relied on."uapi" is the core code of PaddleX. We don't think it's necessary to update the main branch. Of course, we can listen to @jzhang533 's advice.

Please keep in mind that this project has transitioned to being fully community-driven. Seeking consensus and clear public communication in the community is crucial for this new model.

**Comment by cuicheng01** [comment]
> Please keep in mind that this project has transitioned to being fully community-driven. Seeking consensus and clear public communication in the community is crucial for this new model.

Alright, I understand. Thank you all for your remarkable work.  As for the branch issue, we don't think the updates from this specific branch need to be cherry-pick to the main branch at this time. However, if anyone holds a different view, we can discuss it  together. @GreatV

**Comment by GreatV** [comment]
@cuicheng01 Got it.

**Pull request merged**
