### PR TITLE
TextSystem is imported correctly in paddleocr.py

### PR DESCRIPTION
**Pull request by AliBasarann**
### 提PR之前的检查 Check-list

- [ ] 这个 PR 是提交到dygraph分支或者是一个cherry-pick，否则请先提交到dygarph分支。
      This PR is pushed to the dygraph branch or cherry-picked from the dygraph branch. Otherwise, please push your changes to the dygraph branch.
- [ ] 这个PR清楚描述了功能，帮助评审能提升效率。This PR have fully described what it does such that reviewers can speedup.
- [ ] 这个PR已经经过本地测试。This PR can be covered by existing tests or locally verified.

### CODE REVIEW

**Review by tetraxcode — APPROVED** [review]

**Review by tetraxcode — APPROVED** [review]
LGTM

**Comment by jzhang533** [comment]
@AliBasarann thanks for doing this, please sign CLA, so we can merge this PR.

**Comment by AliBasarann** [comment]
Thanks for warning @jzhang533. I signed the CLA.

**Comment by tzktz** [comment]
is latest upadted ? @AliBasarann

**Comment by AliBasarann** [comment]
I could not understand what you mean @tzktz

**Comment by tzktz** [comment]
> I could not understand what you mean @tzktz

TextSystem is imported correctly in paddleocr.py.. I have face the same issue that's why i'm asking is it resolve or not !! @AliBasarann

**Comment by AliBasarann** [comment]
Yes it resolves the issue @tzktz

**Comment by jzhang533** [comment]
BTW: I have yanked v2.7.5 on pypi, I may need to write up a post to discuss with the community how to get this project better maintained.

**Comment by JiaXiao243** [comment]
> I think your fix is correct, But I have no idea why CI-PaddleOCR-Py37-LinuxUbuntu-Cuda102-PR-Release failed. @JiaXiao243 @yinger78
> 
> Personally I am also suffering from this CI infrastructure. We need to invest more on the dev infra for this project.

CI每次会选择3个模型跑训练、评估、预测、动转静、推理全流程，本次 CI 中2个模型成功，1个模型失败，失败配置为configs/rec/rec_vit_parseq.yml
08e4a06aafafe230a16c7faf564d8c8a
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/configs/rec/rec_vit_parseq.yml#L79 部分 data_dir为空，需要修改为./train_data/data_lmdb_release/training/ ，eval部分的 data_dir 需要修改为./train_data/data_lmdb_release/evaluation/

**Comment by jzhang533** [comment]
CI-PaddleOCR-Py37-LinuxUbuntu-Cuda102-PR-Release randomly choose models to run each time, after rerun, this PR turns into green. Will merge.

**Pull request merged**
