### PR TITLE
【do not merge】add german special characters

### LINKED ISSUE #1646: German language model does not return german special characters "äöüß"
Dear all, 

I tried the german language model today. On every image I tried, it was not recognizing the letters 'ÄÖÜäöüß' and was just skipping them.

My very simple code: 

`from paddleocr import PaddleOCR,draw_ocr`

`ocr = PaddleOCR(use_angle_cls=True, lang='german')`

`result = ocr.ocr(filepath, cls=True)`

`strings = []`

`for line in result:`
`strings.append(line[1][0])`

`print(strings)`

All strings just skip these letters, so the word `Grüßen` would be returned as `Gren`. Did I mess something up with the model configuration or is this a bug? 

If you need images for testing, feel free to hit me up.

Thanks in advance! 

Best, 

Justus

### PR DESCRIPTION
**Pull request by Justus-Jonas**
Fixes #1646 

Dear all, 

as discussed with @tink2123, I updated the German dictionary with the German specific special characters. 

If you have any questions feel free to reach out to me.

Best, 

Justus

### CODE REVIEW

**Comment by tink2123** [comment]
@Justus-Jonas  Thanks for your contribution, we will update the model as soon as possible. In order to avoid errors in the prediction of the existing model, the PR will be merged after the release of the new model.

**Comment by saruye** [comment]
@tink2123 I am pretty new here, so just let me know if my question is stupid 😬 is it possible to train the model ourselves? or is it easily possible for you to provide it in a branch? we would like to start a small test with german documents where we would need this fix included. 
Otherwise: is there some rough timeline when this will be merged? (don't want to push, so far this project seems awesome! just for our planning)

**Comment by tink2123** [comment]
@saruye Thanks for your attention. Today we will merge the changes in this PR： https://github.com/PaddlePaddle/PaddleOCR/pull/1767 

> is it possible to train the model ourselves? or is it easily possible for you to provide it in a branch? we would like to start a small test with german documents where we would need this fix included.

You can certainly use this dictionary to train the model by yourselves. If you need any help, please let us know ☺️

**Comment by Justus-Jonas** [comment]
Hi @tink2123, 

do you know when you approx will be able to merge #1646 ? I would like to try it out. 

Many thanks! 

Justus

**Comment by tink2123** [comment]
Hi @Justus-Jonas ,
After using the dictionary you provided, the new model has been trained. There are still some tests to be done, which is expected to be merged in 4 hours.

**Comment by Justus-Jonas** [comment]
Thanks a lot @tink2123! This are good news!

**Comment by xmy0916** [comment]
@Justus-Jonas Thank you for your use. We have finished testing the trained model. Thank you for providing the missing characters. The model will be updated in the morning of January 21~

**Comment by xmy0916** [comment]
@Justus-Jonas  Hello, the model has been updated. The model download path is: https://paddleocr.bj.bcebos.com/dygraph_ v2.0/multilingual/german_ mobile_ v2.0_ rec_ infer.tar
https://paddleocr.bj.bcebos.com/dygraph_ v2.0/multilingual/german_ mobile_ v2.0_ rec_ train.tar
The dictionary path is: https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppocr/utils/dict/german_ dict.txt
We have updated more language models here：
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ en/models_ list_ en.md#multilingual -recognition-modelupdating
Thank you for your use~

**Comment by tink2123** [comment]
Dear @Justus-Jonas , @saruye 

Thanks for your patience，the model has been updated. 
You can try to download the [last model](https://paddleocr.bj.bcebos.com/dygraph_%20v2.0/multilingual/german_mobile_v2.0_rec_%20infer.tar) and try the latest effect:

```
wget https://paddleocr.bj.bcebos.com/dygraph_v2.0/multilingual/german_mobile_v2.0_rec_infer.tar
tar -xf german_mobile_v2.0_rec_infer.tar
python3 tools/infer/predict_rec.py --image_dir="{your/path/of/img}" --rec_model_dir="./your inference model" --rec_char_type="german" --rec_char_dict_path="ppocr/utils/dict/german_dict.txt"
```

If you confirm that there is no problem with the current model, please let us know. We will close this PR.

Many thanks

tink2123

**Comment by Justus-Jonas** [comment]
Dear @tink2123 @xmy0916,

thanks a lot! I am using the python package ` paddleocr-2.0.2 `.  However, the model keeps skipping german special characters, does this happen because the python package is still not updated?

I also tried the new model you provided under the url [german_mobile_v2.0_rec_infer.tar](https://paddleocr.bj.bcebos.com/dygraph_v2.0/multilingual/german_mobile_v2.0_rec_infer.tar), while this one uses ö,ä, etc. it performs compared to the other one really poorly. Is that perhaps because the one you provided is the mobile version and the other is not? 

If I can help in any way, feel free to get back to me.

Thanks a lot!

Justus

**Comment by tink2123** [comment]
Dear @Justus-Jonas ,

Sorry, the python package is still not updated. This need to wait a few more days.

Regarding the recognition performance of the new model is much worse than before, 
there may be some errors in the middle. 

Can you provide a bad-case for us? We will test the effect.

Best,

Tink

**Comment by Justus-Jonas** [comment]
Dear @tink2123, 

thanks a lot for your help! Sorry, my bad, I configured something wrong with the model at first, the results were better than the old german model, but I have still struggle with some things:

The model seems to have big problems with not recognizing spaces which means that it concatenates words. Overall it's doing quite well, it makes mistakes quite frequently but I think this can be only solved by scaling up training data by a lot. Is there a german server model planned?

I want to use the model for extracting text from documents, do you think, I could improve results by fine-tuning the pre-trained model on my documents? If so, how many documents do you think I would need to see a significant improvement? Since I would have to annotate them by myself. 😄 


I would love to share some examples, but the documents are a little confidential, so I would not like them to be freely available on the internet. Is there a way to send them to you directly?

Thanks a lot for your help! 

Best,

Justus

**Comment by tink2123** [comment]
Dear @Justus-Jonas :

I am very glad that the new model can help you！

As you said. The effect of the model is very dependent on the training data. We use imgs of some general scenes during training, which may not have the best effect in your scene.

If you want to get a more suitable model, it is recommended to use your own data to fine-tune the model. If the current model can basically meet your needs, you can only prepare a small amount of data, about 100,000.

At this stage, we currently have no plans to train the server model. Maybe you can try the training yourself, we can communicate at any time when you encounter problems.

In addition, I am very glad that you are willing to provide me with data. You can send an email to me: y_tink@163.com. We will continue to optimize the model with reference to your data.

Best,

Tink

**Pull request closed without merging**
