### PR TITLE
Add Turkish dict and corpora

### PR DESCRIPTION
**Pull request by fcakyon**

### CODE REVIEW

**Comment by grasswolfs** [comment]
> _No description provided._
Hi，could u please provide some corpora？Only the dict is not enough for training a workable model.  T.T

**Comment by fcakyon** [comment]
> > _No description provided._
> > Hi，could u please provide some corpora？Only the dict is not enough for training a workable model.  T.T

I will try to create one

**Comment by fcakyon** [comment]
@grasswolfs added turkish corpora

**Comment by fcakyon** [comment]
@grasswolfs any updates?

**Comment by fcakyon** [comment]
@grasswolfs any updates?

**Comment by fcakyon** [comment]
@grasswolfs any updates?

**Comment by fcakyon** [comment]
@grasswolfs any updates?

**Comment by akdeniz27** [comment]
What is the status of this request?

**Comment by cooleel** [comment]
Any update for this PR?

**Pull request closed without merging**
