### PR TITLE
Update dependency `attrdict` to `attrdict3`

### PR DESCRIPTION
**Pull request by haobibo**
Ref: https://github.com/PaddlePaddle/PaddleOCR/issues/7396

### CODE REVIEW

**Comment by WenmuZhou** [comment]
辛苦也更新一下[ppstructure/kie/requirements.txt](https://github.com/PaddlePaddle/PaddleOCR/blob/56aaead6d06b9ef6c6ecb8655f5a571f579f939e/ppstructure/kie/requirements.txt)，并且cp到dygraph分支

**Comment by haobibo** [comment]
@WenmuZhou  done!
dygraph PR: https://github.com/PaddlePaddle/PaddleOCR/pull/7891

**Comment by haobibo** [comment]
@WenmuZhou  As th PR is merged: https://github.com/PaddlePaddle/PaddleOCR/pull/7891 now, wll this PR  ( https://github.com/PaddlePaddle/PaddleOCR/pull/7416 ) be merged?

**Comment by haobibo** [comment]
@WenmuZhou  any progress?

**Comment by haobibo** [comment]
@tink2123 @Evezerest  could you please consider review and merge this PR?

**Pull request closed without merging**
